from selenium.webdriver.common.by import By


class Locators:
    home = (By.CLASS_NAME, 'fa-home')
    signUp = (By.XPATH, '//*[@id="header"]/div/div/div/div[2]/div/ul/li[4]/a')
    signUpText = (By.LINK_TEXT, 'New User Signup!')
    nameInput = (By.XPATH, '//*[@id="form"]/div/div/div[3]/div/form/input[2]')
    emailInput = (By.XPATH, '//*[@id="form"]/div/div/div[3]/div/form/input[3]')
    signUpButton = (By.XPATH, '//*[@id="form"]/div/div/div[3]/div/form/button')
    accountInfo = (By.LINK_TEXT, 'ENTER ACCOUNT INFORMATION')
    gender = (By.ID, 'id_gender2')
    password = (By.ID, 'password')
    newsletter = (By.ID, 'newsletter')
    day = (By.ID, 'days')
    year = (By.ID, 'years')
    month = (By.ID, 'months')
    offers = (By.ID, 'optin')
    firstName = (By.ID, 'first_name')
    lastName = (By.ID, 'last_name')
    company = (By.ID, 'company')
    address1 = (By.ID, 'address1')
    address2 = (By.ID, 'address2')
    country = (By.ID, 'country')
    state = (By.ID, 'state')
    city = (By.ID, 'city')
    zipCode = (By.ID, 'zipcode')
    mobileNumber = (By.ID, 'mobile_number')
    createAcc = (By.XPATH, '//*[@id="form"]/div/div/div/div/form/button')
    accountCreatedText = (By.LINK_TEXT, 'ACCOUNT CREATED!')
    continueButton = (By.XPATH,'//*[@id="form"]/div/div/div/div/a')
    text = (By.LINK_TEXT, 'Logged in as ')
    delete = (By.XPATH, '//*[@id="header"]/div/div/div/div[2]/div/ul/li[4]/a')
    deleteText = (By.LINK_TEXT, 'ACCOUNT DELETED!')
